
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Akhilesh Mosale
 */
public class empempdisp extends javax.swing.JFrame {

    /**
     * Creates new form empempdisp
     */
    public empempdisp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(840, 374, 77, 31);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(401, 58, 339, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Enter the Employee ID to be Searched:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(85, 57, 304, 18);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Verify");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(750, 50, 85, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Details:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(434, 87, 76, 46);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeId", "Last Name", "First Name", "Position Desc", "Qualification Desc", "Department Name", "Salary", "Commision", "Hire Date", "DOB", "Dependent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 151, 941, 205);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\SQL\\dbms project\\Screenshots\\3.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 480);

        setBounds(0, 0, 977, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
       mainpage obj=new mainpage();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String empid = jTextField2.getText();
        int existing = 0;
        
        
         DefaultTableModel model;
            model=(DefaultTableModel)jTable1.getModel();
        try {
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mini", "root", "root");
            Statement myStat = myConn.createStatement();
            java.sql.ResultSet myRs = myStat.executeQuery("Select * from employee");
            while (myRs.next()) {
                if (myRs.getString("EmployeeID").equals(empid)) {
                    existing++;
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        if (existing == 0) {
            JOptionPane.showMessageDialog(null, "Record not found");
        } else {
            jLabel1.setEnabled(true);
            jButton1.setEnabled(true);
            jTable1.setEnabled(true);
            jLabel4.setEnabled(false);
            jTextField2.setEnabled(false);
            jButton4.setEnabled(false);
            try {
                Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mini", "root", "root");
                CallableStatement cst=myConn.prepareCall("{call proc1("+empid+")}");
                
                ResultSet myRs =cst.executeQuery();
                
                 while(myRs.next())
               {
                   
                   model.addRow(new Object[]{myRs.getString(1),myRs.getString(2),myRs.getString(3),myRs.getString(4),myRs.getString(5),myRs.getString(6),myRs.getString(7),myRs.getString(8),myRs.getString(9),myRs.getString(10),myRs.getString(11)});
               
               
               
               
               }
                /*while (myRs.next()) {
                    jTextArea1.setText("Employee ID:"+myRs.getString(1)+"\nLast Name:"+myRs.getString(2)+"\nFirst Name:"+myRs.getString(3)+"\nPosition Description:"+myRs.getString(8)+"\nQualification:"+myRs.getString(10)
                        +"\nDepartment Name:"+myRs.getString(9)+"\nRelation:"+myRs.getString(11)+"\nSalary:"+myRs.getString(6)+"\nCommission:"+myRs.getString(7)+"\nHire Date:"+myRs.getString(4)+"\nDate of Birth:"+myRs.getString(5));
                }*/

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empempdisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empempdisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empempdisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empempdisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empempdisp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
